### ISSUE TITLE
Message for invalid siteswaps

### ISSUE THREAD

**Issue by amiel** [JugglerRick/SiteSwapTranslator#2]
Currently, when entering an invalid siteswap, the translator goes ahead with the calculations. It would be nice to have a message when the pattern is invalid.

In case it helps, here is a simple (possibly not the most efficient), siteswap pattern validator in javascript:
https://github.com/amiel/siteswapgame/blob/master/app/assets/javascripts/siteswapgame.js#L4-L17

**Comment by j-c-stuifbergen** [comment]
...  I use the calculateNumberOfProps method and verify that the the output is an integer value.....
That is not a sufficient check.

I have corrected it in my local version (actually copying the validator that amien mentioned)

**Comment by JugglerRick** [comment]
I am sorry I was sick all day yesterday and am currently at work and do not
have time to deal with this now. I will going to the first local juggling
meeting in 3 weeks tonight but I will at least get the pull approved late
to night (I am in the GMT -8 time zone)
Thank you for your help in correcting these issues.

Rick
