### ISSUE TITLE
Add simplest translation form

### ISSUE THREAD

**Issue by amiel** [JugglerRick/SiteSwapTranslator#3]
While the pattern form `< 3 2.5d 3.5d 3 2.5b 3.5b | 3.5a 3 2.5c 3.5c 3 2.5a >` is very descriptive of the full pattern, I find it handy to look at the simplest form (ie `2.5p 3.5p 3`).

**Comment by j-c-stuifbergen** [comment]
I have managed to reduce the output to 
< 3 2.5px 3.5p  | 3.5px 3 2.5p   >
but I must still upload my code.
A reduction to 3.5p 3 2.5p is possible (note that the 'x' apply to different passes for differen jugglers) only if both jugglers juggle the same site-swap.
e.g. not if the global site-swap is 8677
